# Use Node.js base
FROM node:20-alpine

WORKDIR /app

RUN npm install -g serve

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

EXPOSE 3000
CMD ["serve", "-s", "dist", "-l", "3000"]